In [1]:
import numpy as np

In [2]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [3]:
print(x)

[[1 2]
 [3 4]]


In [5]:
x.size

4

In [6]:
x.shape

(2, 2)

In [7]:
x=np.array([[1,2,3],[3,4,5]])
x

array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
x.shape

(2, 3)

In [9]:
x.size

6

In [12]:
x.dtype

dtype('int32')

In [13]:
type(x)

numpy.ndarray

In [14]:
x.ndim

2

In [30]:
y=np.array([[[1,2,3],[3,4,5],[7,8,9]]])
print(y.ndim)

3


In [20]:
y.ndim

2

In [18]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [21]:
x.ndim

2

In [22]:
x.shape

(2, 2)

In [23]:
y.shape

(3, 3)

In [24]:
y.size

9

In [25]:
y.ndim

2

In [26]:
print(y.ndim)

2


In [28]:
print(y)

[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [31]:
print(y)

[[[1 2 3]
  [3 4 5]
  [7 8 9]]]


In [32]:
z=np.array([[2.2,3.3],[4.4,5.5]])
print(z)

[[2.2 3.3]
 [4.4 5.5]]


In [33]:
type(z)

numpy.ndarray

In [34]:
z.shape

(2, 2)

In [35]:
z.size

4

In [36]:
z.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [37]:
z.ndim

2

In [38]:
z.dtype

dtype('float64')

In [39]:
a=np.zeros(shape=(2,3), dtype='int',order='c')

In [40]:
a

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
a1=np.zeros(shape=(2,3), dtype='int',order='c')
a1

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
print(a1)

[[0 0 0]
 [0 0 0]]


In [43]:
print(a)

[[0 0 0]
 [0 0 0]]


In [45]:
a2=np.zeros(shape=(2,3), dtype='int',order='F')
a2

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
print(a2)

[[0 0 0]
 [0 0 0]]


In [56]:
b=np.arange(50,100)
b

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
b[10]

60

In [49]:
b=np.arange(50,100,2)
print(b)

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [50]:
b[10]

70

In [52]:
b.dtype

dtype('int32')

In [59]:
type(b)

numpy.ndarray

In [58]:
b.shape

(50,)

In [57]:
b.size


50

In [60]:
b[5:48:2]

array([55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87,
       89, 91, 93, 95, 97])

In [61]:
b[5:50:3]

array([55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [62]:
b[40:]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [63]:
c=np.array([3,4,5,6,7,9,8,5,1,2])
c.size

10

In [64]:
c[6:]

array([8, 5, 1, 2])

In [65]:
c[6:9]

array([8, 5, 1])

In [66]:
c[-2:]

array([1, 2])

In [67]:
c[-4:]

array([8, 5, 1, 2])

In [68]:
c[-4:-2]

array([8, 5])

In [69]:
c[-4:-1]

array([8, 5, 1])

In [70]:
d=c
print(d)

[3 4 5 6 7 9 8 5 1 2]


In [71]:
e=np.copy(d)

In [72]:
print(e)

[3 4 5 6 7 9 8 5 1 2]


In [73]:
a=a*3

In [74]:
print(a)

[[0 0 0]
 [0 0 0]]


In [75]:
c=c*3

In [76]:
print(c)

[ 9 12 15 18 21 27 24 15  3  6]


In [77]:
print(d)

[3 4 5 6 7 9 8 5 1 2]


In [78]:
print(e)

[3 4 5 6 7 9 8 5 1 2]


In [79]:
d*5
print(d)

[3 4 5 6 7 9 8 5 1 2]


In [80]:
e[2]=44

In [81]:
print(e)

[ 3  4 44  6  7  9  8  5  1  2]


In [82]:
print(d)

[3 4 5 6 7 9 8 5 1 2]


In [83]:
org_array=np.array([2,33,5,66,77])

In [84]:
print(org_array)

[ 2 33  5 66 77]


In [91]:
mod_array=np.ndarray(5,dtype='object')

In [92]:
mod_array[:]=org_array

In [93]:
mod_array[1]=19
mod_array[4]=77

In [94]:
print(org_array)
print(mod_array)

[ 2 33  5 66 77]
[2 19 5 66 77]


In [95]:
org_array.dtype

dtype('int32')

In [96]:
mod_array.dtype

dtype('O')

In [98]:
mod_array1=np.ndarray(5)
print(org_array)
print(mod_array)
print(mod_array1)

[ 2 33  5 66 77]
[2 19 5 66 77]
[ 2. 19.  5. 66. 77.]


In [101]:
mod_arr2=org_array.copy()

In [102]:
print(mod_arr2)

[ 2 33  5 66 77]


In [4]:
x=np.empty(shape=[2,2], dtype=int)
print(x)

[[0 0]
 [0 0]]


In [5]:
y=np.zeros(shape=[3,3], dtype=float)
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
z=np.ones(shape=[4,3],dtype=int)
print(z)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [19]:
x1=np.arange(start=100,stop=10000,step=100,dtype=int)
print(x1)

[ 100  200  300  400  500  600  700  800  900 1000 1100 1200 1300 1400
 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800
 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200
 4300 4400 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600
 5700 5800 5900 6000 6100 6200 6300 6400 6500 6600 6700 6800 6900 7000
 7100 7200 7300 7400 7500 7600 7700 7800 7900 8000 8100 8200 8300 8400
 8500 8600 8700 8800 8900 9000 9100 9200 9300 9400 9500 9600 9700 9800
 9900]


In [11]:
print(np.linspace(1,10))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [15]:
print(np.linspace(1,20))

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


In [33]:
a=np.empty(shape=[3,1],dtype=int,order='C')
b=np.zeros(shape=[3,1],dtype=int)
c=np.ones(shape=[3,1],dtype=int)
print(a,b,c)

[[1]
 [1]
 [1]] [[0]
 [0]
 [0]] [[1]
 [1]
 [1]]


In [35]:
x=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
y=np.array([x[0,0],x[0,1],x[2,2],x[2,2]])
print(y)

[0 1 8 8]


In [53]:
x=np.array([[1,2],[3,4],[5,6]])
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [43]:
print(x.reshape((2,3)))

[[1 2 3]
 [4 5 6]]


In [54]:
print(x.resize(2,3))

None


In [55]:
x=np.ones((3,4))
print(x)
y=x.flatten()
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [57]:
x=np.ones((3,4,5))
print(x)
print("ravel",x.ravel())

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
ravel [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [62]:
x=np.ones([2,3])
print(x)
print(x.T)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [64]:
x=np.array([[1,2],[3,4]])
print(np.linalg.inv(x))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [69]:
x=np.zeros((2,3))
print(x)
y=np.ones((2,3))
print(y)
print(np.hstack((x,y)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [70]:
print(np.vstack((x,y)))

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [72]:
x=np.empty((1,3))
y=np.ones((1,3))
z=np.zeros((1,3))
print(np.vstack((x,y,z)))

[[ 1.04619885e-311  0.00000000e+000 -6.47591605e-319]
 [ 1.00000000e+000  1.00000000e+000  1.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]]


In [75]:
x=np.array([[42,22,12],[44,53,66]])
print(x.reshape(3,2))
print(x.T)
print(x.flatten())

[[42 22]
 [12 44]
 [53 66]]
[[42 44]
 [22 53]
 [12 66]]
[42 22 12 44 53 66]


In [83]:
y=np.array([[42,22,12],[44,53,66]])
print(np.hstack(y))

[42 22 12 44 53 66]


In [81]:
x=np.array([[42,22,12],[44,53,66]])
print(np.vstack(x))

[[42 22 12]
 [44 53 66]]


In [91]:
x=np.arange(1,50)
print(x)
y=np.where(x>20)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48], dtype=int64),)


In [87]:
print(x>7)

[False False False False False False False  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True]


In [92]:
x=np.array([1,2,3,4])
print(x)
print(np.cumsum(x))
print(np.cumproduct(x))

[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [93]:
x=np.array([2,3,4,5,23,4,1,2,3])
print(x)
print(np.unique(x))

[ 2  3  4  5 23  4  1  2  3]
[ 1  2  3  4  5 23]


In [95]:
x=np.array(['hi','how','hi','how'])
print(x)
print(np.unique(x))

['hi' 'how' 'hi' 'how']
['hi' 'how']


In [96]:
x=np.array([[2,3,4,5],[4,5,6,7]])
print(x)
print(np.min(x))
print(np.max(x))
print(np.sum(x))

[[2 3 4 5]
 [4 5 6 7]]
2
7
36


In [97]:
print(np.argmin(x))
print(np.argmax(x))

0
7


In [98]:
print(np.sort(x,0))

[[2 3 4 5]
 [4 5 6 7]]


In [99]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
print(a)
print(np.where(a>7))

[[ 1  2  4  7]
 [ 9 88  6 45]
 [ 9 76  3  4]]
(array([1, 1, 1, 2, 2], dtype=int64), array([0, 1, 3, 0, 1], dtype=int64))


In [100]:
print(a>7)

[[False False False False]
 [ True  True False  True]
 [ True  True False False]]


In [101]:
print(np.where(a<=5))

(array([0, 0, 0, 2, 2], dtype=int64), array([0, 1, 2, 2, 3], dtype=int64))


In [102]:
print(np.cumsum(a))

[  1   3   7  14  23 111 117 162 171 247 250 254]


In [103]:
print(np.unique(a))

[ 1  2  3  4  6  7  9 45 76 88]


In [105]:
print(np.sort(a))

[[ 1  2  4  7]
 [ 6  9 45 88]
 [ 3  4  9 76]]


In [106]:
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.argmin(a))
print(np.argmax(a))


1
88
254
0
5


In [112]:
from numpy import random
random.seed(8)
print(random.rand(3))

[0.8734294  0.96854066 0.86919454]


In [111]:
from numpy import random

print(random.rand(3))

[0.43046882 0.40235136 0.52267467]


In [113]:
print(random.randint(5,20,5))

[13  8 13  5 18]


In [114]:
c=np.arange(30)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [123]:
print(np.random.binomial(9,0.1,10))

[0 0 0 3 0 0 0 0 1 2]


In [124]:
x=np.arange(30)
print(x)
np.save('myfile.npy',x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [125]:
y=np.load('myfile.npy')
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [1]:
import numpy as np

In [3]:
a=np.array([[1,2,4,7],[9,88,6,4,5],[9,76,3,4]])
np.unique(a)

array([list([1, 2, 4, 7]), list([9, 76, 3, 4]), list([9, 88, 6, 4, 5])],
      dtype=object)

In [7]:
a=np.array([1.,2])
b=np.arange(8)
print(np.in1d(a,b))

[ True  True]


In [8]:
print(np.intersect1d(a,b))

[1. 2.]


In [10]:
print(a)
print(b)

[1. 2.]
[0 1 2 3 4 5 6 7]


In [9]:
print(np.union1d(a,b))

[0. 1. 2. 3. 4. 5. 6. 7.]


In [12]:
a=np.array([1.,2])
b=np.arange(8)
print(np.setdiff1d(a,b))
print(np.setdiff1d(b,a))

[]
[0 3 4 5 6 7]


In [14]:
np.setxor1d(a,b)

array([0., 3., 4., 5., 6., 7.])

In [2]:
a=np.array([1,2,3,4,5,6])
power = 2
answer = (a[a%2==1])**power
print (answer)

NameError: name 'np' is not defined