In [1]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [3]:
y=np.arange(0,10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
z=np.full((3,3),True, dtype=bool)
print(z)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


TypeError: data type "true" not understood

In [6]:
a=np.array([1,2,3,4,5,6])
answer = (a[a%2!=0])
print (answer)

[1 3 5]


SyntaxError: invalid syntax (<ipython-input-8-f608ccc2bcaa>, line 3)

In [10]:
np.where(a%2==0,a,-2)

array([-2,  2, -2,  4, -2,  6])

In [13]:
arr=np.array([1,2,3,4,5,6])
np.reshape(arr,[2,3])

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a=np.array([1,2,3,4,5,6,7,8,9])
[x for x in a if x % 2 != 0 or x % 4 == 0  ]

[1, 3, 4, 5, 7, 8, 9]

In [27]:
np.isnan(arr)

array([False, False, False, False, False, False])

In [28]:
arr5=np.array([1,2,3,4,5,6,np.nan])

In [29]:
np.isnan(arr5)

array([False, False, False, False, False, False,  True])

In [31]:
np.nan_to_num(arr5,0)

array([1., 2., 3., 4., 5., 6., 0.])

In [34]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)
 
# Get a tuple of unique values & their frequency in numpy array
uniqueValues, occurCount = np.unique(arr, return_counts=True)
 
print("Unique Values : " , uniqueValues)
print("Occurrence Count : ", occurCount)

Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
Occurrence Count :  [3 2 2 2 1 1 1 1]


In [39]:
x=np.array([1,2,3,4,5])
x.dtype

dtype('int32')

In [42]:
x=np.array(x,dtype='object')

In [45]:
x.dtype

dtype('O')

In [49]:
y=np.arange(99,299)
#print(y)
[x for x in y if x % 5 != 0 or x %7 != 0  ]

[99,
 100,
 101,
 102,
 103,
 104,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,

In [50]:
ar=np.arange(0,9)
res=ar[::-1]

In [51]:
res

array([8, 7, 6, 5, 4, 3, 2, 1, 0])